version: 2
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: frameskip/ci-build:1.0
    working_directory: /home/frameskip
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Run tests
          command: gradle test
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Assemble JAR
          command: gradle assemble
      - store_artifacts:
          path: build/libs/frameskip-1.0-SNAPSHOT.jar
          destination: frameskip-1.0-SNAPSHOT.jar
workflows:
  version: 2
  build:
    jobs:
      - build
