version: 2
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: frameskip/ci-build:4.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Run tests
          command: gradle test
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Assemble JAR
          command: gradle assemble
      - run:
          name: Build Frameskip Docker image
          command: docker build --tag gcr.io/frameskip/base-image .
      - run:
          name: Authenticate gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      - run: gcloud auth configure-docker
      - run:
          name: Push Docker image to Google Container Registry
          command: docker push gcr.io/frameskip/base-image

  checkstyle-analysis:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: frameskip/ci-build:4.0
    steps:
      - checkout
      - run:
          name: "Run Checkstyle"
          command: "gradle checkstyleMain checkstyleTest"

  deploy-to-prod:
    docker:
      - image: frameskip/ci-build:4.0
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      - run:
          name: Deploy container to Cloud Run
          command: gcloud beta run deploy frameskip --image gcr.io/frameskip/base-image --project frameskip --platform managed --region us-east1 --allow-unauthenticated

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - checkstyle-analysis
      - promote-to-prod:
          type: approval
          requires:
            - build
            - checkstyle-analysis
          filters:
            branches:
              only: master
      - deploy-to-prod:
          requires:
            - promote-to-prod
