version: 2
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Run tests
          command: gradle test
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Assemble JAR
          command: gradle assemble
      - store_artifacts:
          path: build/libs/frameskip-1.0-SNAPSHOT.jar
          destination: frameskip-1.0-SNAPSHOT.jar
  deploy:
    docker:
      - image: frameskip/ci-build:1.0
    steps:
      - run: echo $CIRCLE_PREVIOUS_BUILD_NUM
      - run: echo $CIRCLE_TOKEN
      - run:
          name: Download artifact
          command: curl https://circleci.com/api/v1.1/project/github/oxfist/frameskip/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts?circle-token=$CIRCLE_TOKEN | grep -o 'https://[^"]*' | sed -e "s/$/?circle-token=$CIRCLE_TOKEN/" | wget -v -i -

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
